### ISSUE TITLE
IOError: Error retrieving entities from: http://ner.kbresearch.nl/?

### ISSUE THREAD

**Issue by loveJasmine** [KBNLresearch/dac#1]
mldl@ub1604:~/ub16_prj/dac/dac$ python dac.py
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-08-26 11:58:55.645223: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-08-26 11:58:55.697519: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-26 11:58:55.697823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.55GiB
2018-08-26 11:58:55.697857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2018-08-26 11:58:55.818855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "dac.py", line 1908, in <module>
    pprint(linker.link(vars(args)['url'], vars(args)['ne']))
  File "dac.py", line 99, in link
    self.context = Context(url, ne)
  File "dac.py", line 295, in __init__
    self.get_entities()
  File "dac.py", line 335, in get_entities
    TPTA_URL))
IOError: Error retrieving entities from: http://ner.kbresearch.nl/?
mldl@ub1604:~/ub16_prj/dac/dac$

**Comment by WillemJan** [comment]
Might be, the endpoint is a test/demo-server, we don't monitor our application well enough to ensure each call get's the correct response. The NER service can be found here [https://github.com/KBNLresearch/Trias_NER] , if you intend on using it for a large corpus. It might be a hassle to install, for it relies on 3 working NER algorthims (Mostly Python) but the main one, Stanford (With custom training data) is a bit harder to setup, but we're willing to help if that is required.
